lint:
  rules:
    no_default: false
    add:
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - FILE_NAMES_LOWER_SNAKE_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - PACKAGE_NAME_LOWER_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - REPEATED_FIELD_NAMES_PLURALIZED
      - QUOTE_CONSISTENT
      - INDENT
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PROTO3_GROUPS_AVOID
      - MAX_LINE_LENGTH
    remove:
      - IMPORTS_SORTED
      - ORDER
    # Linter rules option.
  rules_option:
    indent:
      style: 4
